import { Session } from "inspector";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "../components/SessionProvider";
import { getServerSession } from "next-auth";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <main className="mx-auto flex gap-2 text-white">
            <Nav />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
