import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "../components/SessionProvider";
import { getServerSession } from "next-auth";
import Nav from "@/components/Nav";
import { authOptions } from "./api/auth/[...nextauth]/route";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="mx-auto flex min-h-screen bg-slate-300">
            <Nav />
            <div className="flex-grow p-4 bg-slate-500 rounded-xl m-4">{children}</div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
